---
title: "DSPP - Hurricane Analysis"
author: "Taketo"
date: "3/4/2020"
output:
  html_document: default
    code_folding: hide
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Data Processing

```{r message=FALSE}
# load packages
library(HURDAT)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(plotly)
library(ggthemes)
```

### All Storms Dataset

```{r paged.print=TRUE}
# get hurricanes data using hurdat package
hurs_all <- get_hurdat("AL")
write_csv(hurs_all, "hurricanes_raw.csv")

# examine data
#print("Here's a summary of each variable")
#summary(hurs_all) # there are lots of NAs for everything after "Pressure" variable
hurs_all <- hurs_all %>% arrange(Key)

# get separate date, year, month, day, and hour variables
hurs_all$Date <- date(hurs_all$DateTime)
hurs_all$Year <- year(hurs_all$DateTime)
hurs_all$Month <- month(hurs_all$DateTime)
hurs_all$Day <- day(hurs_all$DateTime)
hurs_all$Hour <- hour(hurs_all$DateTime)

hurs_all <- hurs_all[, c(1:3, 22:26, 4:21)]

# recode Record and Status variables
hurs_all <- hurs_all %>%
  mutate(Record = recode(Record, "L" = "Landfall")) %>%
  mutate(Status = recode(Status,
                         "TD" = "Tropical depression (<34 knots)",
                         "TS" = "Tropical storm (34-63 knots)",
                         "HU" = "Tropical Hurricane (>= 64 knots)",
                         "EX" = "Extratropical cyclone",
                         "SD" = "Subtropical depression (<34 knots)",
                         "SS" = "Subtropical storm (>= 34 knots)",
                         "LO" = "Low",
                         "WV" = "Tropical Wave",
                         "DB" = "Disturbance"
                         ))

# tabulate Record and Status variables
#print("Tabulation of Record and Status variables")
#table(hurs_all$Record, useNA="always")
#table(hurs_all$Status, useNA="always")
```

### Dataset with only Hurricanes (wind > 64 knots)

```{r}
big_hurs_list <- hurs_all %>% 
  filter(Status =="Tropical Hurricane (>= 64 knots)") %>%
  .[, 1] %>% 
  unique(.)
length(big_hurs_list)
hurs_big <- hurs_all[hurs_all$Key %in% big_hurs_list, ]
write_csv(hurs_big, "hurricanes_big.csv")
```

### Landfall Hurricanes Dataset

```{r paged.print=TRUE}
# create dataset with hurricanes that reached land
landfall_list <- hurs_big[hurs_big$Record=="Landfall", 1]
hurs_landfall <- hurs_big[hurs_big$Key %in% landfall_list, ]
```

### Mapping of Landfalls

```{r}
map <- subset(hurs_all, Record == "Landfall")
map <- subset(map, Wind >= 64)
map <- subset(map, Lat >= 24)
map <- subset(map, Lon <= -65)

us.states <- ggplot2::map_data("state")
g1 <- ggplot() + 
  geom_polygon(data=us.states, aes(x=long, y=lat, group=group), 
               color = "grey", fill = NA) + 
  geom_point(data=map, aes(x=Lon ,y=Lat), size=map$Wind/40,
             alpha=map$Wind/160, color="blue") + 
  xlab("longitude") + ylab("latitude") + 
  coord_cartesian(xlim=c(-110, -65)) + 
  ggtitle("Hurricane Landfalls (1851-2018)") + theme_classic()
g1

png("image/g1.png", width = 350, height = 300)
g1
dev.off()
```

### Clustering of Landfalls

```{r}
cluster <- read.csv("cluster1.csv") # data from python code

g2 <- ggplot() + 
  geom_polygon(data = us.states, aes(x=long, y=lat, group=group), 
               color = "grey", fill = NA) + 
  geom_point(data=cluster, aes(x=Lon ,y=Lat), fill=cluster$Colour, 
             size=cluster$Number/3.4, alpha=0.5, color=cluster$Colour) + 
  xlab("longitude") + ylab("latitude") + 
  coord_cartesian(xlim=c(-100, -65)) + 
  ggtitle("Clustering Hurricane Landfalls") + theme_classic()
g2

png("image/g2.png", width = 350, height = 300)
g2
dev.off()
```

### Geocoding

```{r}
library(sp)
library(maps)
library(maptools)

latlong2county <- function(pointsDF) {
    counties <- map('county', fill=TRUE, col="transparent", plot=FALSE)
    IDs <- sapply(strsplit(counties$names, ":"), function(x) x[1])
    counties_sp <- map2SpatialPolygons(counties, IDs=IDs,
                     proj4string=CRS("+proj=longlat +datum=WGS84"))
    pointsSP <- SpatialPoints(pointsDF, 
                    proj4string=CRS("+proj=longlat +datum=WGS84"))
    indices <- over(pointsSP, counties_sp)
    countyNames <- sapply(counties_sp@polygons, function(x) x@ID)
    countyNames[indices]
}

#hurs_geocode <- hurs_landfall
#hurs_geocode$County <- 0
#hurs_geocode <- hurs_geocode[, c(1:9,27,10:26)]

#for (i in 14001:15027) {
#  tmp <- data.frame(x=hurs_geocode$Lon[i], y=hurs_geocode$Lat[i])
#  hurs_geocode$County[i] <- latlong2county(tmp)
#}

#write_csv(hurs_geocode, "hurricanes_geocode15000.csv")
#hurs_geocode <- hurs_geocode[, c(1:15)]
#write_csv(hurs_geocode, "hurs_geocode.csv")
```

### Create Ranking

```{r}
h <- read.csv("hurs_geocode.csv")
ranking = aggregate(h$Key, by=list(h$County), FUN=length)
colnames(ranking) = c("county", "number")
sortlist <- order(ranking$number, decreasing=TRUE)
ranking <- ranking[sortlist,]

h64 <- subset(h, Wind >= 64)
ranking64 = aggregate(h64$Key, by=list(h64$County), FUN=length)
colnames(ranking64) = c("county", "number")
sortlist <- order(ranking64$number, decreasing=TRUE)
ranking64 <- ranking64[sortlist,]
write_csv(ranking64, "ranking64.csv")

h60 <- subset(h64, Year >= 1960)
ranking60 = aggregate(h60$Key, by=list(h60$County), FUN=length)
colnames(ranking60) = c("county", "number")
sortlist <- order(ranking60$number, decreasing=TRUE)
ranking60 <- ranking60[sortlist,]
```

### County Mapping

```{r}
library(urbnmapr)
# Returns a ggplot2 object with a geom_map of the the lower 
# 48 states (plus Hawaii & Alaska reset on the bottom) 
# uscounties_sf <- get_urbn_map("counties", sf = TRUE)

rf <- read.csv("ranking64fips.csv")
rf$FIPS <- as.character(rf$FIPS)
rf$FIPS[16] <- "01003"
rf$FIPS[45] <- "01099"
rm <- left_join(rf, counties, by = c("FIPS" = "county_fips"))

gg <- rm %>%
  ggplot(aes(long, lat, group = group, fill = number)) +
  geom_polygon(color = "black", size=0.0125) +
  scale_fill_gradientn(colours=c("blue","purple2","red"), 
           name="Number of Hurricanes") + theme_classic()

gg <- gg + theme(legend.position = c(0.8, 0.3)) + 
  ggtitle("Counties passed over by Hurricanes (> 64 knots)") +
  theme(plot.title = element_text(hjust=0.5, size=20),
        legend.title = element_text(size=15))

gg <- gg + 
  geom_polygon(data = urbnmapr::states,
               mapping = aes(x = long, y = lat, group = group),
               fill = NA, color = "black", size=0.0125) + 
  coord_cartesian(xlim=c(-100, -60), ylim=c(23, 45))
gg

png("image/gg.png", width = 650, height = 400)
gg
dev.off()
```

### Impact on poverty rate

```{r}
h_plaque <- subset(h64, County == "louisiana,plaquemines")
h_collier <- subset(h64, County == "florida,collier")
h_martin <- subset(h64, County == "florida,martin")

year <- c(1960,1970,1980,1990,2000,2010)
poverty <- c(33.3,17.0,15.4,22.6,18.0,11.0)
p_plaque <- data.frame(Year=year, Poverty_rate=poverty)
poverty <- c(31.0,16.0,13.6,10.5,10.3,14.0)
p_collier <- data.frame(Year=year, Poverty_rate=poverty)
poverty <- c(28.3,19.8,11.1,8.3,8.8,12.5)
p_martin <- data.frame(Year=year, Poverty_rate=poverty)

g3 <- ggplot(p_plaque, aes(x=Year, y=Poverty_rate)) + 
  geom_bar(stat="identity", fill="blue") + 
  annotate("text", x=1988, y=27, col="red", label="FLORENCE \n (1988)") +
  annotate("text", x=2005, y=22, col="red", label="KATRINA \n (2005)") + 
  annotate("text", x=2017, y=15, col="red", label="NATE \n (2017)") + 
  xlab("Year") + ylab("Poverty rate (%)") + 
  coord_cartesian(xlim=c(1960,2020)) + 
  ggtitle("Poverty rate at Plaquemines (LA)") + theme_hc()
g3

g4 <- ggplot(p_collier, aes(x=Year, y=Poverty_rate)) + 
  geom_bar(stat="identity", fill="blue") + 
  annotate("text", x=1960, y=36, col="red", label="DONNA \n (1960)") +
  annotate("text", x=2005, y=20, col="red", label="WILMA \n (2005)") + 
  xlab("Year") + ylab("Poverty rate (%)") + 
  coord_cartesian(xlim=c(1955,2010), ylim=c(0,40)) + 
  ggtitle("Poverty rate at Collier (FL)") + theme_hc()
g4

g5 <- ggplot(p_martin, aes(x=Year, y=Poverty_rate)) + 
  geom_bar(stat="identity", fill="blue") + 
  annotate("text", x=1999, y=12,   col="red", label="IRENE \n (1999)") +
  annotate("text", x=2004, y=18.5, col="red", 
           label="FRANCES \n & JEANNE \n (2004)") + 
  xlab("Year") + ylab("Poverty rate (%)") + 
  coord_cartesian(xlim=c(1960,2010)) + 
  ggtitle("Poverty rate at Martin (FL)") + theme_hc()
g5

png("image/g3.png", width = 400, height = 300)
g3
dev.off()
png("image/g4.png", width = 400, height = 300)
g4
dev.off()
png("image/g5.png", width = 400, height = 300)
g5
dev.off()
```

```{r}
#test <- read.csv("test.csv")
```